---

- include: dotfiles.yml
- include: homebrew.yml
- include: osx-tools.yml

- name: Ensure everything in ~/.dotfiles/ is sourced in ~/.bash_profile
  lineinfile: dest=~/.bash_profile create=yes line='for file in ~/.dotfiles/*; do if [ -f "$file" ]; then . $file; fi; done'
