---
- name: OSX | Install homebrew applications
  homebrew:
    name:
      - git
      - glances
      - hub
      - jq
      - spark
      - tree
      - watch
      - wget
    state: latest
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'

- name: OSX | Install homebrew cask applications
  homebrew_cask:
    name:
      - 1password
      - bitbar
      - caffeine
      - flux
      - gimp
      - iterm2
      - rectangle
      - signal
    state: upgraded
  when: ansible_os_family == 'Darwin'

- name: OSX | Install apps managed by my work via cask if not installed
  homebrew_cask:
    name:
      - google-chrome
    state: upgraded
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'

- name: Add bitbar plugins
  copy: src=bitbar dest=~/ mode=0744

- name: Add hub dotfile
  copy: src=hub.dotfile dest=~/.dotfiles/ mode=0644
