---
- name: OSX | Install homebrew applications
  homebrew: name={{ item }} state=present
  with_items:
    - hub
    - jq
    - tree
    - watch
    - wget
  when: ansible_os_family == 'Darwin'

- name: OSX | Install homebrew cask applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - caffeine
    - flux
    - gimp
    - google-chrome
    - iterm2
    - sketchup
    - slack
    - zazu
  when: ansible_os_family == 'Darwin'

- name: Arch | Install applications
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - hub
    - terminator
    - xclip
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'

- name: Add hub dotfile
  copy: src=hub.dotfile dest=~/.dotfiles/ mode=0644
