language: minimal

matrix:
  include:
    - os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ansible; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make run; fi