language: ruby

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

install:
  - easy_install pip
  - pip install ansible

script:
  - echo $TRAVIS_OS_NAME
  - make update run
