language: ruby

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

install:
  - sudo easy_install pip
  - sudo pip install setuptools ansible

script:
  - echo $TRAVIS_OS_NAME
  - make run
