language: ruby

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ansible; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo easy_install pip && pip install --upgrade setuptools && pip install ansible; fi

script:
  - make run
