tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "fcanas/tap"

# Common tools
brew "antigen"
brew "mas"
brew "bat"
brew "php"
brew "fcanas/tap/mirror-displays"
cask "1password"
cask "xbar"
cask "caffeine"
cask "docker"
cask "inkscape"
cask "gimp"
cask "iterm2"
cask "rectangle"
cask "signal"
cask "notion"
cask "bartender"
cask "vivaldi"
cask "divvy"
cask "alfred"
cask "spotify"
cask "zoom"

