tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Common tools
cask "1password"
cask "bitbar"
cask "caffeine"
cask "docker"
cask "flux"
cask "inkscape"
cask "gimp"
cask "google-chrome"
cask "iterm2"
cask "rectangle"
cask "signal"
cask "station"