---
- hosts: all

# I may not be able to do this using just ansible
# if variable file exists
#   no: ask to install each role.
#     yes: install the role
#     write choices variables file
#   yes: use the variables in variables file and prompt if there are any missing

  roles:
    - common-tools
    - dev-tools
