---
- src: https://github.com/funkymonkeymonk/ansible-common-tools.git
  path: remote-roles
  name: common-tools

- src: https://github.com/funkymonkeymonk/ansible-dev-tools.git
  path: remote-roles
  name: dev-tools

- src: https://github.com/funkymonkeymonk/ansible-entertainment.git
  path: remote-roles
  name: entertainment
