---
- name: OSX | Install atom
  homebrew_cask: name=atom state=present
  when: ansible_os_family == 'Darwin'

# Need to figure out how to install atom on arch programmatically
# Currently manually using the AUR

- name: Check if atom is installed
  command: which atom
  register: atom_is_installed
  ignore_errors: yes

# apm command source - https://github.com/hnakamur/ansible-role-atom-packages
- name: Install atom packages
  apm: name={{item}} state=latest
  with_items:
    - ansible-snippets
    - auto-indent
    - git-plus
    - language-docker
    - language-terraform
    - linter
    - markdown-writer
    - minimap
    - minimap-git-diff
    - script
    - travis-ci-status
  when: atom_is_installed.rc == 0
