---

- name: OSX | Install apps
  homebrew: name={{ item }} state=latest update_homebrew=yes
  with_items:
    - awscli
    - heroku-toolbelt

- name: OSX | Install cask apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - gitup
