- name: OSX | Install scala
  homebrew:
    name:
      - scala
      - sbt
    state: latest
    update_homebrew: yes
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'

- name: Arch | Install scala
  pacman:
    name:
      - scala
      - sbt
    state: latest
    update_cache: yes
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'

- name: Add scala plugins
  copy: src=plugins.sbt dest=~/.sbt/0.13/plugins/ mode=0644
